// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJBAB9jvow6he4WHEH-k04tZZY3GyZcm0',
    appId: '1:1091244269702:web:b1429ccddfb14c74243107',
    messagingSenderId: '1091244269702',
    projectId: 'muk-student-loan',
    authDomain: 'muk-student-loan.firebaseapp.com',
    storageBucket: 'muk-student-loan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU7vdgV0lP_cNWEo9SWWuXLEbEDJtaZhA',
    appId: '1:1091244269702:android:90f740465988e933243107',
    messagingSenderId: '1091244269702',
    projectId: 'muk-student-loan',
    storageBucket: 'muk-student-loan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO1Rd1teY6zA5LPhPx_fnKK77DFgXU3xo',
    appId: '1:1091244269702:ios:dfea5fe0f9ce53dd243107',
    messagingSenderId: '1091244269702',
    projectId: 'muk-student-loan',
    storageBucket: 'muk-student-loan.appspot.com',
    iosBundleId: 'com.example.makScholar1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO1Rd1teY6zA5LPhPx_fnKK77DFgXU3xo',
    appId: '1:1091244269702:ios:ffb56dd9ce3c3c71243107',
    messagingSenderId: '1091244269702',
    projectId: 'muk-student-loan',
    storageBucket: 'muk-student-loan.appspot.com',
    iosBundleId: 'com.example.makScholar1.RunnerTests',
  );
}
